export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const ACCESS_TOKEN_EXPIRED = process.env.ACCESS_TOKEN_EXPIRED;

export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
export const REFRESH_TOKEN_EXPIRED = process.env.REFRESH_TOKEN_EXPIRED;
export const CLOUDINARY_SECRET_KEY = process.env.CLOUDINARY_SECRET_KEY;

console.log({
	ACCESS_TOKEN_SECRET,
	ACCESS_TOKEN_EXPIRED,
	REFRESH_TOKEN_SECRET,
	REFRESH_TOKEN_EXPIRED,
	CLOUDINARY_SECRET_KEY,
});
